AWSTemplateFormatVersion: '2010-09-09'
Description: Create a webserver EC2 instance with an instance store

Resources:
  SystemVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: SystemVPC

  PrivateSubnet1a:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref SystemVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: "us-east-1a"
      Tags:
        - Key: Name
          Value: private_subnet_1a

  PrivateRouteTable1a:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref SystemVPC
      Tags:
        - Key: Name
          Value: private_route_table_1a

  PrivateRouteTableAssociation1a:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet1a
      RouteTableId: !Ref PrivateRouteTable1a

  SecurityGroupSSM:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for SSM interface endpoint
      VpcId: !Ref SystemVPC
      SecurityGroupIngress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: !GetAtt SystemVPC.CidrBlock

  SSMEndpointSystemVPC:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref SystemVPC
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ssm
      VpcEndpointType: Interface
      SubnetIds:
        - !Ref PrivateSubnet1a
      SecurityGroupIds:
        - !Ref SecurityGroupSSM
      PrivateDnsEnabled: true

  SSMMessagesEndpointSystemVPC:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref SystemVPC
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ssmmessages
      VpcEndpointType: Interface
      SubnetIds:
        - !Ref PrivateSubnet1a
      SecurityGroupIds:
        - !Ref SecurityGroupSSM
      PrivateDnsEnabled: true

  EC2MessagesEndpointSystemVPC:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref SystemVPC
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ec2messages
      VpcEndpointType: Interface
      SubnetIds:
        - !Ref PrivateSubnet1a
      SecurityGroupIds:
        - !Ref SecurityGroupSSM
      PrivateDnsEnabled: true

  EC2InstanceRoleSSM:
    Type: AWS::IAM::Role
    Properties:
      RoleName: EC2S3AccessRoleSSM
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  EC2InstanceProfileSSM:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: EC2S3AccessInstanceProfileSSM
      Roles:
        - !Ref EC2InstanceRoleSSM

  WebserverEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0532be01f26a3de55
      InstanceType: c5d.large
      SubnetId: !Ref PrivateSubnet1a
      IamInstanceProfile: !Ref EC2InstanceProfileSSM
      BlockDeviceMappings:
        # 1. The default Root Volume (EBS)
        - DeviceName: '/dev/xvda'
          Ebs:
            VolumeSize: 20
            VolumeType: 'gp3'
        # 2. The Instance Store Volume Mapping
        - DeviceName: '/dev/sdb'
          VirtualName: 'ephemeral0'
      Tags:
        - Key: Name
          Value: private_instance
      UserData:
        Fn::Base64: |
          #!/bin/bash
          # Ensures the SSM agent is installed and running
          sudo yum install -y amazon-ssm-agent
          sudo systemctl enable amazon-ssm-agent
          sudo systemctl start amazon-ssm-agent
