AWSTemplateFormatVersion: '2010-09-09'
Description: Prepare the EC2 instance for EC2 Instance Connect

Resources:
  SystemVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.1.0.0/16
      Tags:
        - Key: Name
          Value: SystemVPC

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: SystemIGW

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref SystemVPC
      InternetGatewayId: !Ref InternetGateway
  
  PublicSubnet1a:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref SystemVPC
      CidrBlock: 10.1.1.0/24
      AvailabilityZone: "us-east-1a"
      Tags:
        - Key: Name
          Value: public_subnet_1a

  PublicRouteTable1a:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref SystemVPC
      Tags:
        - Key: Name
          Value: public_route_table_1a

  PublicSubnetRouteTableAssociation1a:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1a
      RouteTableId: !Ref PublicRouteTable1a

  PublicInternetRoute1a:
    Type: AWS::EC2::Route
    DependsOn: VPCGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable1a
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  SystemSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow EC2 Instance Connect
      VpcId: !Ref SystemVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 18.206.107.24/29
      Tags:
        - Key: Name
          Value: EC2InstanceConnectSecurityGroup

  WebserverEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0532be01f26a3de55
      InstanceType: t2.micro
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: "0"
          GroupSet:
            - !Ref SystemSecurityGroup
          SubnetId: !Ref PublicSubnet1a
      Tags:
        - Key: Name
          Value: ec2_instance_connect_webserver
