AWSTemplateFormatVersion: '2010-09-09'
Description: >
  CloudFormation template to create an IAM Role for STS with specific permissions.
Resources:
  STSRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: STSAssumeRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:user/cloud_user'
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess'
