AWSTemplateFormatVersion: '2010-09-09'
Description: Create an new VPC
Resources:
  SimpleVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/24
      Tags:
        - Key: Name
          Value: SimpleVPC